apiVersion: v2
name: webapp-chart
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.23"
keywords:
  - web
  - nginx
  - production
maintainers:
  - name: student
    email: student@universicty.edu
