apiVersion: v1
kind: Service
metadata:
  name: {{ include "webapp-chart.fullname" . }}
  labels:
    {{- include "webapp-chart.labels" . | nindent 4 }}
    {{- if .Values.extraLabels.enabled }}
    {{- range $key, $value := .Values.extraLabels.custom }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
    {{- end }}
    environment: {{ .Values.labels.environment }}
    team: {{ .Values.labels.team }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "webapp-chart.selectorLabels" . | nindent 4 }}
    {{- if .Values.extraLabels.enabled }}
    {{- range $key, $value := .Values.extraLabels.custom }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
    {{- end }}
